<!--
	Filename: confirmation.inc
	Author: Nilay Sondagar
	Date: September 15, 2018
	Purpose: Shows the confirmation page for the Duck Tracker website.
-->


<div id="confirmbox">
	<br>
	Thank you for submitting your duck data!
	<img id="confirmicon" src="ConfirmIcon.png"/>
	
	<form action="index.php" method="get" id="databutton">
		<button type="submit" name="showdata" value="data" class="button">See Data</button>
	</form>

</div>