<!DOCTYPE html>
  <html>
  <head>
    <meta charset="utf-8">
    <title>DuckTracker</title>
    <link rel="stylesheet" href="styles.css">  
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Sunflower:300|Montserrat|Bungee+Outline|Bungee+Hairline|Roboto:300" rel="stylesheet">
    <link rel="ICON" href="images/NS Logo.png" type="image/png">
  </head>
  
  <body>