<!--
 * Filename: header.inc
 * Author: Nilay Sondagar
 * Date Created: September 5, 2018
 * Purpose: Contains the header information/tags for the Duck Tracker website.
 -->

<!DOCTYPE html>
  <html>
  <head>
    <meta charset="utf-8">
    <title>DuckTracker</title>
    <link rel="stylesheet" href="styles.css">  
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Sunflower:300|Montserrat|Bungee+Outline|Bungee+Hairline|Roboto:300" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="script.js"></script>
    <link rel="ICON" href="images/NS Logo.png" type="image/png">
    <meta name="viewport" 
content="width=device-width, height=device-height, initial-scale=1">
  </head>
  
  <body>